Fixes to correctly install and execute switch tests

diff --git a/run_switchtests b/run_switchtests
--- a/run_switchtests
+++ b/run_switchtests
@@ -1,7 +1,11 @@
 #!/bin/bash
-for M in model-*.glm; do
+if [ $# -eq 0 ]; then
+	echo "Syntax: $(basename $0) model-num ..."
+	exit
+fi
+for M in $*; do
 	for F in switchtest/switchtest_*.glm; do
 		N=$(echo $F | sed 's/[^0-9]//g' )
-		echo gridlabd -D SWITCHTEST=yes -D SWITCHINIT=$N $M
+		gridlabd -D SWITCHTEST=yes -D SWITCHINIT=$N $M || echo "Test $N failed."
 	done
 done
